/**
 * Tokens alinhados ao layout de referência efood (EBAC / Figma).
 * Ajuste fino pode ser feito comparando Inspect do Figma lado a lado com a página.
 */
export const theme = {
  colors: {
    bg: '#FFF8F2',
    primary: '#E66767',
    text: '#E66767',
    textOnDark: '#FFFFFF',
    white: '#FFFFFF',
    peach: '#FFEBD9',
    overlay: 'rgba(0, 0, 0, 0.5)',
    overlayModal: 'rgba(0, 0, 0, 0.8)',
    star: '#FFB930',
    footerText: '#E66767',
    heroStripe: 'rgba(230, 103, 103, 0.07)',
  },
  font: {
    family: "'Roboto', system-ui, sans-serif",
  },
  typography: {
    logo: {
      fontSize: '36px',
      fontWeight: 700,
      letterSpacing: '-0.5px',
    },
    heroTitle: {
      fontSize: '36px',
      fontWeight: 900,
      lineHeight: '42px',
    },
    headerSideText: {
      fontSize: '18px',
      fontWeight: 900,
      lineHeight: 1,
      letterSpacing: '0',
    },
    restaurantCardTitle: {
      fontSize: '18px',
      fontWeight: 700,
      lineHeight: 1.22,
    },
    restaurantCardBody: {
      fontSize: '14px',
      fontWeight: 400,
      lineHeight: 1.43,
    },
    productCardTitle: {
      fontSize: '16px',
      fontWeight: 900,
      lineHeight: 1,
    },
    productCardBody: {
      fontSize: '14px',
      fontWeight: 400,
      lineHeight: '22px',
    },
    bannerCategory: {
      fontSize: '32px',
      fontWeight: 100,
      lineHeight: 1,
    },
    bannerTitle: {
      fontSize: '32px',
      fontWeight: 900,
      lineHeight: 1,
    },
    footerDisclaimer: {
      fontSize: '10px',
      fontWeight: 400,
      lineHeight: 1,
    },
    buttonPrimary: {
      fontSize: '14px',
      fontWeight: 700,
      lineHeight: 1.14,
    },
    buttonSecondary: {
      fontSize: '14px',
      fontWeight: 700,
      lineHeight: '16px',
    },
    rating: {
      fontSize: '18px',
      fontWeight: 700,
      lineHeight: 1,
    },
    tag: {
      fontSize: '12px',
      fontWeight: 700,
      lineHeight: 1.33,
    },
  },
  spacing: {
    xs: '8px',
    sm: '16px',
    md: '24px',
    lg: '32px',
    xl: '48px',
    xxl: '80px',
    containerPaddingX: '24px',
    gridGapHomeRow: '48px',
    gridGapHomeCol: '80px',
    gridGapRestaurant: '32px',
    sectionPaddingBottom: '120px',
    restaurantSectionPaddingTop: '56px',
    headerHomePaddingTop: '40px',
    headerRestaurantPaddingY: '32px',
    headerHeight: '186px',
    footerPaddingTop: '40px',
    footerPaddingBottom: '40px',
    footerLogoToSocial: '32px',
    footerSocialToDisclaimer: '80px',
    cardPaddingRestaurant: '8px',
    cardPaddingProduct: '8px',
    heroMarginTop: '64px',
    heroMarginBottom: '56px',
    heroPaddingY: '48px',
    heroPaddingX: '24px',
    heroTitleMaxWidth: '540px',
    tagGap: '8px',
    tagOffsetX: '16px',
    tagOffsetY: '16px',
  },
  radii: {
    button: '0px',
    tag: '0px',
  },
  sizes: {
    restaurantCardImageHeight: '217px',
    bannerMinHeight: '280px',
    socialIconCircle: '24px',
    socialIconGlyph: '14px',
    productImageAspectRatio: '1 / 1',
    productCardWidth: '320px',
    productCardMinHeight: '338px',
    productImageHeight: '167px',
    productInnerWidth: '304px',
    productButtonHeight: '24px',
    modalImageSize: '280px',
    modalPanelMaxWidth: '1024px',
    modalPanelMinHeight: '344px',
    disclaimerMaxWidth: '480px',
    footerMinHeight: '298px',
    logoImgWidth: '125px',
    logoImgHeight: '57.5px',
    headerCartMaxWidth: '256px',
    restaurantCardWidth: '472px',
    restaurantCardHeight: '398px',
  },
  layout: {
    maxWidth: '1024px',
  },
} as const

export type Theme = typeof theme
